### ISSUE TITLE
Prodigal-gv and Prodigal issue

### ISSUE THREAD

**Issue by raw937** [gbouras13/pharokka#317] opened 2023-12-22 21:11 UTC
* pharokka version: 1.5.1v
* Python version: 3.10 
* Operating System: Linux

### Description

Traceback (most recent call last):
  File "/home/docwhite/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 220, in _na_arithmetic_op
    result = func(left, right)
  File "/home/docwhite/.local/lib/python3.10/site-packages/pandas/core/computation/expressions.py", line 242, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "/home/docwhite/.local/lib/python3.10/site-packages/pandas/core/computation/expressions.py", line 73, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docwhite/miniconda3/envs/pharokka/bin/pharokka.py", line 496, in <module>
    main()
  File "/home/docwhite/miniconda3/envs/pharokka/bin/pharokka.py", line 312, in main
    translate_fastas(out_dir, gene_predictor, args.coding_table, args.infile)
  File "/home/docwhite/miniconda3/envs/pharokka/bin/processes.py", line 553, in translate_fastas
    clean_df = tidy_prodigal_output(out_dir, False)  # gv_flag is false
  File "/home/docwhite/miniconda3/envs/pharokka/bin/processes.py", line 433, in tidy_prodigal_output
    prod_filt_df["contig"]
  File "/home/docwhite/.local/lib/python3.10/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
  File "/home/docwhite/.local/lib/python3.10/site-packages/pandas/core/arraylike.py", line 186, in __add__
    return self._arith_method(other, operator.add)
  File "/home/docwhite/.local/lib/python3.10/site-packages/pandas/core/series.py", line 5815, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "/home/docwhite/.local/lib/python3.10/site-packages/pandas/core/base.py", line 1381, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/home/docwhite/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 285, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
  File "/home/docwhite/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 229, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
  File "/home/docwhite/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 165, in _masked_arith_op
    result[mask] = op(xrav[mask], yrav[mask])
TypeError: unsupported operand type(s) for +: 'int' and 'str'

Similar to the one last night about int and str for prodigal. 

### What I Did

```
pharokka.py -i MUT.fna -o MUT_phk_fgv -d ~/miniconda3/envs/pharokka/databases/ -t 8 --fast -g prodigal
pharokka.py -i MUT.fna -o MUT_phk_fgv -d ~/miniconda3/envs/pharokka/databases/ -t 8 --fast -g prodigal-gv
```

**Comment by gbouras13** [comment] 2024-01-10 00:34
Hi @raw937 ,

I can reproduce your error.

The issue I believe is that the contig name/id is an integer, and that the type is ambiguous in that function (tidy_prodigal_output) in pharokka, which breaks some of the post processing glue code. 

e.g. either of the below will cause an error:

```
>1 
ACT
>2 depth=1.00x
GCCT
```

There's some other dodgy typing in pharokka (I wasn't an especially great coder back when I wrote it, a little better now but still not great!),  I've had to fix a few other downstream instances as a result.

 I have had this issue reported a while back (particularly in the context of annotating the output from Unicycler directly, as Unicycler gives integer headers) - I had thought I'd fixed it but clearly not!

I've tested and pushed a fix, it will be available in v1.6. 

If you want to run v1.5.1/don't want to wait for v1.6, I suggest changing the headers of your input FASTA.

If this is not the cause, please also let me know. 

George

**Closed** 2024-01-10 23:00 UTC
Labels: bug
