### ISSUE TITLE
Error with Phanotate (return code 1)

### ISSUE THREAD

**Issue by Norina28** [gbouras13/pharokka#350] opened 2024-06-27 15:44 UTC
* pharokka version: 1.7.2
* Python version: Python 3.10.14
* Operating System: Linux
* Phanotate version: v1.5.1

### Description

I am trying to run pharokka (w/ & w/o fast option) on SA genomes but I always get this same error: 
....
2024-06-27 15:15:05.043 | INFO     | __main__:main:280 - Running Phanotate.
2024-06-27 15:15:05.046 | INFO     | external_tools:run:50 - Started running phanotate.py -f fasta -o /home/ecella/ATB/SAMD00009489_pharrokka2/phanotate_out_tmp.fasta ./SAMD00009489.fa ...
2024-06-27 15:22:58.067 | ERROR    | external_tools:run_tool:94 - Error calling phanotate.py -f fasta -o /home/SAMD00009489_pharrokka2/phanotate_out_tmp.fasta ./SAMD00009489.fa (return code 1)
2024-06-27 15:22:58.069 | ERROR    | processes:run_phanotate:291 - Error with Phanotate

### What I Did

```
pharokka.py -i ./SAMD00009489.fa -d ~/pharokka_v1.4.0_databases -o ~/ATB/SAMD00009489_pharrokka2 -t 16 --fast
```
Thank you so much

**Comment by kakadaisy** [comment] 2024-07-08 11:38
I have encountered the same problem. Have you resolved it，please？

**Comment by gbouras13** [comment] 2024-07-08 12:10
Hi @kakadaisy @Norina28 ,

Are you running Pharokka on entire SA (Staph aureus?) bacterial genomes? Phanotate is not designed for large bacterial sized chromosomes. 

If you are indeed running Pharokka on phage genome isolates, then this is certainly a big problem :) If so, would you be able to upload an example input FASTA so I can reproduce the errors?

George

**Comment by Norina28** [comment] 2024-07-08 15:55
Hi @gbouras13 thank you for your reply. Yes, I was running Pharokka on the complete Staph aureus genomes. Okay, then this explains a lot.  ◡̈
I'll find a tool to extract the phage genomes and then I'll run it.
Thank you!

Ele

**Comment by gbouras13** [comment] 2024-07-09 01:43
No problem - I'd use something like PhiSpy or Genomad :). 

Closing this issue now.

George

**Closed by gbouras13** 2024-07-09 01:43 UTC

**Comment by kakadaisy** [comment] 2024-07-09 09:46
Hello, @gbouras13 thank you for your reply. I ran it after removing the genome of the host bacteria. This is the genome I used, and I uploaded my phage genome. Could you please help me check what the problem is? Thank you
[Uploading P-20N5.zip…]()
