### ISSUE TITLE
An error after proccesing after processing hhsuite

### ISSUE THREAD

**Issue by kohei-108** [gbouras13/pharokka#140] opened 2022-07-09 04:14 UTC
* phrokka version: 0.1.4
* Python version: Python 3.9.13
* Operating System: Ubuntu 18.04.5 LTS

### Description

I tried pharokka but I encountered a bug after processing hhsuite.

The log is as follows.

```
Starting pharokka.
FASTA checked
Running Phanotate.
Running tRNAscan-SE.
Running mmseqs2.
Running hhsuite.
Processing mmseqs2 output.
Processing hhsuite output.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/pharokka/bin/pharokka.py", line 68, in <module>
    post_processing.create_txt(phan_mmseq_merge_df, length_df,out_dir, prefix)
  File "/home/ubuntu/miniconda3/envs/pharokka/bin/modules/post_processing.py", line 148, in create_txt
    phanotate_mmseqs_df_cont[['attributes2','function']] = phanotate_mmseqs_df_cont['attributes2'].str.split(';function=',expand=True)
  File "/home/ubuntu/miniconda3/envs/pharokka/lib/python3.9/site-packages/pandas/core/frame.py", line 3643, in __setitem__
    self._setitem_array(key, value)
  File "/home/ubuntu/miniconda3/envs/pharokka/lib/python3.9/site-packages/pandas/core/frame.py", line 3685, in _setitem_array
    check_key_length(self.columns, key, value)
  File "/home/ubuntu/miniconda3/envs/pharokka/lib/python3.9/site-packages/pandas/core/indexers/utils.py", line 428, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
```

### What I Did

I used viral contigs using by VirSorter2 from metagenome sequences.

```
$ nohup pharokka.py -i ./checkv-results/vs2-results-pass2/final-viral-combined.fa -d /mnt/pharokka-db/ -o pharokka-results -t 16 &
```

Header of fasta is as follows.

```
>k141_91663||full_1
>k141_591542||full_1
......
```

**Comment by gbouras13** [comment] 2022-07-09 04:29
Hi Kohei,

Would you be able to attach or email me the pharokka .log file (it should be in the output directory pharokka-results). And if it exists, the .gff file.

From what you have posted, it looks like pharokka may have found 0 database hits for at least 1 contig and this is causing an error in creating the summary output function. The "main" part of pharokka (the gff file) should have worked and should exist in the output directory.

George

**Comment by gbouras13** [comment] 2022-07-09 04:57
Hi Kohei,

I have replicated the error with some "mock" viral meta genome fastas, so no need to upload the log files. 

I was correct - the issue is because at least one of your contigs has no predicted genes.

I will work on a fix for this issue and let you know when it is ready.

George
George

**Comment by kohei-108** [comment] 2022-07-09 06:05
Hi George,
Thanks, that would be very helpful!

**Closed** 2022-07-09 09:02 UTC

**Comment by gbouras13** [comment] 2022-07-09 10:51
Hi Kohei,

I have updated pharokka (v=0.1.5). This should fix this issue. Try updating pharokka

conda install -c gbouras13 pharokka=0.1.5

and give your metagenome sequences another go.
