### ISSUE TITLE
[hhsuite] cluster consensus error

### ISSUE THREAD

**Issue by lxsteiner** [gbouras13/pharokka#149] opened 2022-07-19 13:13 UTC
* phrokka version: 0.1.5 (conda)
* Python version: Python 3.9.13
* Operating System: Ubuntu 14.04.6 LTS (GNU/Linux 4.4.0-148-generic x86_64)

### Description

Describe what you were trying to get done.

- Annotating a phage genome from a single contig.

Tell us what happened, what went wrong, and what you expected to happen.

- `hhsuite` runs into an error: 
```
2022-07-19 12:26:19,687 - INFO - Starting hhsuite
2022-07-19 12:26:19,690 - INFO - data file: pharokka_annot/hhsuite_target_dir/hhsuite_tsv_file.ffdata
2022-07-19 12:26:19,690 - INFO - index file: pharokka_annot/hhsuite_target_dir/hhsuite_tsv_file.ffindex
2022-07-19 12:26:19,690 - INFO - fasta file: pharokka_annot/phanotate_aas_tmp.fasta
2022-07-19 12:26:19,713 - INFO - - 12:26:19.713 INFO: Searching 38880 column state sequences.
2022-07-19 12:26:19,713 - INFO -
2022-07-19 12:26:20,318 - INFO - - 12:26:20.318 INFO: Thread 0  cluster_001_consensusdelim0
2022-07-19 12:26:20,318 - INFO -
2022-07-19 12:26:20,907 - INFO - - 12:26:20.905 INFO: cluster_001_consensusdelim0 is in A2M, A3M or FASTA format
2022-07-19 12:26:20,907 - INFO -
2022-07-19 12:26:20,940 - INFO - - 12:26:20.939 ERROR: In /opt/conda/conda-bld/hhsuite_1645696999782/work/src/hhalignment.cpp:511: Read:
2022-07-19 12:26:20,940 - INFO -
2022-07-19 12:26:20,940 - INFO - - 12:26:20.940 ERROR:  MSA file cluster_001_consensusdelim0 contains no master sequence!
2022-07-19 12:26:20,940 - INFO -
```
Seems to be related to issues in #140 and #101. I had the same error happen with <0.1.5 versions. Is this maybe fixed in 0.1.6 from a few days ago?

### What I Did
```
$ pharokka.py -i 8_medaka.fasta -o pharokka_annot -d /media/5c679734-9376-4617-815c-d4bd4177b8b2/leon/projects/06/soft/pharokkaDB -t 32 -p T3
Starting pharokka.
FASTA checked
Phanotate will be used for gene prediction
Running Phanotate.
Running tRNAscan-SE.
Running mmseqs2.
Running hhsuite.
Processing mmseqs2 output.
Processing hhsuite output.
Traceback (most recent call last):
  File "/home/leon/miniconda3/envs/pharokka_env/bin/pharokka.py", line 77, in <module>
    phan_mmseq_merge_df = post_processing.process_results(DBDIR, out_dir, prefix, gene_predictor)
  File "/home/leon/miniconda3/envs/pharokka_env/bin/modules/post_processing.py", line 80, in process_results
    tophits_hmm__df[['spl','ind']] = tophits_hmm__df['gene_hmm'].str.split('delim',expand=True)
  File "/home/leon/miniconda3/envs/pharokka_env/lib/python3.9/site-packages/pandas/core/frame.py", line 3643, in __setitem__
    self._setitem_array(key, value)
  File "/home/leon/miniconda3/envs/pharokka_env/lib/python3.9/site-packages/pandas/core/frame.py", line 3685, in _setitem_array
    check_key_length(self.columns, key, value)
  File "/home/leon/miniconda3/envs/pharokka_env/lib/python3.9/site-packages/pandas/core/indexers/utils.py", line 428, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
```

Thanks!

**Comment by gbouras13** [comment] 2022-07-19 14:11
Hi lxsteiner,

It is clear that you have an error with hh-suite. It does not appear to be related to #140 and #101.

I have been able to re-create the error with a contig on my machine named "cluster_001_consensus" - your issue seems to be caused by the contig header and so is similar to #89.

For now I suggest you rename the fasta header of 8_medaka.fasta to something else. I will work on a fix for this for v1.0.7 - I imagine you won't be the only one to use medaka output (I probably will myself!)

Just to let you know, v1.0.6 is substantially same as v1.0.5 but was created as an initial release for bioconda. I am awaiting review for now, hopefully it gets approved soon.

George

**Closed** 2022-07-20 03:14 UTC

**Comment by gbouras13** [comment] 2022-07-20 03:17
I believe that I have fixed this in the latest commit - please let me know if it works for you now. 

You will have to clone the GitHub repo and run pharokka from there until I push a new version to bioconda (running it in same conda environment as your original installation for all the dependencies should be fine). 

If your phage has trnas, the contig names in the gff are likely to be different for now - I will implement a fix for this soon #103.

George

**Comment by gbouras13** [comment] 2022-07-20 08:54
Hi lxsteiner,

I actually have completely removed hh-suite as a dependency, so if you use the GitHub repo this should now work with no issue on your original file.

George

**Comment by lxsteiner** [comment] 2022-09-19 09:32
A bit late but I just wanted to follow up - thank you for looking into it and addressing the issue. I used version 0.1.10 (bioconda) and everything worked out fine!
